backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "halaman_berita"
    label: "Berita"
    files:
      - label: "Daftar Berita"
        name: "berita"
        file: "data/berita.json" # Semua berita akan disatukan di file ini
        fields:
          - label: "Kumpulan Berita"
            name: "items"
            widget: "list"
            fields:
              - {label: "Judul Berita", name: "title", widget: "string"}
              - {label: "Tanggal", name: "date", widget: "datetime"}
              - {label: "Gambar Thumbnail", name: "thumbnail", widget: "image"}
              - {label: "Deskripsi Singkat", name: "description", widget: "text"}
              - {label: "Isi Berita Lengkap", name: "body", widget: "markdown"}