backend:
  name: github
  repo: ryanfauzi-TIK/web-tik-vokasi
  branch: main
  base_url: https://web-tik-vokasi.netlify.app

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "berita"
    label: "Berita"
    files:
      - file: "public/data/berita.json"
        label: "Daftar Berita"
        name: "daftar-berita"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Deskripsi Singkat", name: "description", widget: "string" }
              - { label: "Tanggal", name: "date", widget: "datetime" }
              - { label: "Gambar Mini", name: "thumbnail", widget: "image" }
              - { label: "Isi Berita Lengkap", name: "body", widget: "markdown" }

  - name: "dosen"
    label: "Dosen"
    files:
      - file: "public/data/dosen.json"
        label: "Daftar Dosen"
        name: "daftar-dosen"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Nama Lengkap", name: "nama", widget: "string" }
              - { label: "Jabatan", name: "jabatan", widget: "string" }
              - { label: "Foto", name: "foto", widget: "image" }

  - name: "fasilitas"
    label: "Fasilitas"
    files:
      - file: "public/data/fasilitas.json"
        label: "Daftar Fasilitas"
        name: "daftar-fasilitas"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Nama Fasilitas", name: "nama", widget: "string" }
              - { label: "Gambar Fasilitas", name: "gambar", widget: "image" }