backend:
  name: github
  repo: ryanfauzi-TIK/web-tik-vokasi
  branch: main
  base_url: https://auth.decapcms.org

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "berita"
    label: "Berita"
    folder: "public/data/posts"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar", name: "thumbnail", widget: "image" }
      - { label: "Isi", name: "body", widget: "markdown" }

  - name: "dosen"
    label: "Dosen"
    folder: "public/data/dosen"
    create: true
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Jabatan", name: "jabatan", widget: "string" }
      - { label: "Foto", name: "foto", widget: "image" }

  - name: "fasilitas"
    label: "Fasilitas"
    folder: "public/data/fasilitas"
    create: true
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Gambar", name: "gambar", widget: "image" }